"""Typed kind hints generated from an Infrahub schema.

Generated by scripts/generate_kinds.py - do not edit by hand.
Source: https://sandbox.infrahub.app (Infrahub 1.10.6)

The kind annotations exist only for static analysis (autocomplete, type
checking); no attributes are created at runtime. Api.__getattr__ builds
every KindEndpoint dynamically, so kinds missing from this list - anything
another instance's schema defines - still work, and the hint classes in
hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aiopyinfrahub import hints_generated as hints


class KindHints:
    """One annotation per schema kind, inherited by Api."""

    BuiltinIPAddress: hints.BuiltinIPAddressEndpoint
    BuiltinIPNamespace: hints.BuiltinIPNamespaceEndpoint
    BuiltinIPPrefix: hints.BuiltinIPPrefixEndpoint
    BuiltinTag: hints.BuiltinTagEndpoint
    CoreAccount: hints.CoreAccountEndpoint
    CoreAccountGroup: hints.CoreAccountGroupEndpoint
    CoreAccountRole: hints.CoreAccountRoleEndpoint
    CoreAction: hints.CoreActionEndpoint
    CoreArtifact: hints.CoreArtifactEndpoint
    CoreArtifactCheck: hints.CoreArtifactCheckEndpoint
    CoreArtifactDefinition: hints.CoreArtifactDefinitionEndpoint
    CoreArtifactTarget: hints.CoreArtifactTargetEndpoint
    CoreArtifactThread: hints.CoreArtifactThreadEndpoint
    CoreArtifactValidator: hints.CoreArtifactValidatorEndpoint
    CoreBasePermission: hints.CoreBasePermissionEndpoint
    CoreChangeComment: hints.CoreChangeCommentEndpoint
    CoreChangeThread: hints.CoreChangeThreadEndpoint
    CoreCheck: hints.CoreCheckEndpoint
    CoreCheckDefinition: hints.CoreCheckDefinitionEndpoint
    CoreComment: hints.CoreCommentEndpoint
    CoreCredential: hints.CoreCredentialEndpoint
    CoreCustomWebhook: hints.CoreCustomWebhookEndpoint
    CoreDataCheck: hints.CoreDataCheckEndpoint
    CoreDataValidator: hints.CoreDataValidatorEndpoint
    CoreEnvKeyValue: hints.CoreEnvKeyValueEndpoint
    CoreFileCheck: hints.CoreFileCheckEndpoint
    CoreFileObject: hints.CoreFileObjectEndpoint
    CoreFileThread: hints.CoreFileThreadEndpoint
    CoreGeneratorAction: hints.CoreGeneratorActionEndpoint
    CoreGeneratorAwareGroup: hints.CoreGeneratorAwareGroupEndpoint
    CoreGeneratorCheck: hints.CoreGeneratorCheckEndpoint
    CoreGeneratorDefinition: hints.CoreGeneratorDefinitionEndpoint
    CoreGeneratorGroup: hints.CoreGeneratorGroupEndpoint
    CoreGeneratorInstance: hints.CoreGeneratorInstanceEndpoint
    CoreGeneratorValidator: hints.CoreGeneratorValidatorEndpoint
    CoreGenericAccount: hints.CoreGenericAccountEndpoint
    CoreGenericRepository: hints.CoreGenericRepositoryEndpoint
    CoreGlobalPermission: hints.CoreGlobalPermissionEndpoint
    CoreGraphQLQuery: hints.CoreGraphQLQueryEndpoint
    CoreGraphQLQueryGroup: hints.CoreGraphQLQueryGroupEndpoint
    CoreGroup: hints.CoreGroupEndpoint
    CoreGroupAction: hints.CoreGroupActionEndpoint
    CoreGroupTriggerRule: hints.CoreGroupTriggerRuleEndpoint
    CoreIPAddressPool: hints.CoreIPAddressPoolEndpoint
    CoreIPPool: hints.CoreIPPoolEndpoint
    CoreIPPrefixPool: hints.CoreIPPrefixPoolEndpoint
    CoreKeyValue: hints.CoreKeyValueEndpoint
    CoreMenu: hints.CoreMenuEndpoint
    CoreMenuItem: hints.CoreMenuItemEndpoint
    CoreNode: hints.CoreNodeEndpoint
    CoreNodeTriggerAttributeMatch: hints.CoreNodeTriggerAttributeMatchEndpoint
    CoreNodeTriggerMatch: hints.CoreNodeTriggerMatchEndpoint
    CoreNodeTriggerRelationshipMatch: hints.CoreNodeTriggerRelationshipMatchEndpoint
    CoreNodeTriggerRule: hints.CoreNodeTriggerRuleEndpoint
    CoreNumberPool: hints.CoreNumberPoolEndpoint
    CoreObjectComponentTemplate: hints.CoreObjectComponentTemplateEndpoint
    CoreObjectPermission: hints.CoreObjectPermissionEndpoint
    CoreObjectTemplate: hints.CoreObjectTemplateEndpoint
    CoreObjectThread: hints.CoreObjectThreadEndpoint
    CorePasswordCredential: hints.CorePasswordCredentialEndpoint
    CoreProfile: hints.CoreProfileEndpoint
    CoreProposedChange: hints.CoreProposedChangeEndpoint
    CoreReadOnlyRepository: hints.CoreReadOnlyRepositoryEndpoint
    CoreRepository: hints.CoreRepositoryEndpoint
    CoreRepositoryGroup: hints.CoreRepositoryGroupEndpoint
    CoreRepositoryValidator: hints.CoreRepositoryValidatorEndpoint
    CoreResourcePool: hints.CoreResourcePoolEndpoint
    CoreSchemaCheck: hints.CoreSchemaCheckEndpoint
    CoreSchemaValidator: hints.CoreSchemaValidatorEndpoint
    CoreStandardCheck: hints.CoreStandardCheckEndpoint
    CoreStandardGroup: hints.CoreStandardGroupEndpoint
    CoreStandardWebhook: hints.CoreStandardWebhookEndpoint
    CoreStaticKeyValue: hints.CoreStaticKeyValueEndpoint
    CoreTaskTarget: hints.CoreTaskTargetEndpoint
    CoreThread: hints.CoreThreadEndpoint
    CoreThreadComment: hints.CoreThreadCommentEndpoint
    CoreTransformJinja2: hints.CoreTransformJinja2Endpoint
    CoreTransformPython: hints.CoreTransformPythonEndpoint
    CoreTransformation: hints.CoreTransformationEndpoint
    CoreTriggerRule: hints.CoreTriggerRuleEndpoint
    CoreUserValidator: hints.CoreUserValidatorEndpoint
    CoreValidator: hints.CoreValidatorEndpoint
    CoreWebhook: hints.CoreWebhookEndpoint
    CoreWeightedPoolResource: hints.CoreWeightedPoolResourceEndpoint
    InfraAutonomousSystem: hints.InfraAutonomousSystemEndpoint
    InfraBGPPeerGroup: hints.InfraBGPPeerGroupEndpoint
    InfraBGPSession: hints.InfraBGPSessionEndpoint
    InfraBackBoneService: hints.InfraBackBoneServiceEndpoint
    InfraCircuit: hints.InfraCircuitEndpoint
    InfraCircuitEndpoint: hints.InfraCircuitEndpointEndpoint
    InfraDevice: hints.InfraDeviceEndpoint
    InfraEndpoint: hints.InfraEndpointEndpoint
    InfraInterface: hints.InfraInterfaceEndpoint
    InfraInterfaceL2: hints.InfraInterfaceL2Endpoint
    InfraInterfaceL3: hints.InfraInterfaceL3Endpoint
    InfraLagInterface: hints.InfraLagInterfaceEndpoint
    InfraLagInterfaceL2: hints.InfraLagInterfaceL2Endpoint
    InfraLagInterfaceL3: hints.InfraLagInterfaceL3Endpoint
    InfraMlagDomain: hints.InfraMlagDomainEndpoint
    InfraMlagInterface: hints.InfraMlagInterfaceEndpoint
    InfraMlagInterfaceL2: hints.InfraMlagInterfaceL2Endpoint
    InfraMlagInterfaceL3: hints.InfraMlagInterfaceL3Endpoint
    InfraPlatform: hints.InfraPlatformEndpoint
    InfraService: hints.InfraServiceEndpoint
    InfraVLAN: hints.InfraVLANEndpoint
    IpamIPAddress: hints.IpamIPAddressEndpoint
    IpamIPPrefix: hints.IpamIPPrefixEndpoint
    IpamNamespace: hints.IpamNamespaceEndpoint
    LineageOwner: hints.LineageOwnerEndpoint
    LineageSource: hints.LineageSourceEndpoint
    LocationContinent: hints.LocationContinentEndpoint
    LocationCountry: hints.LocationCountryEndpoint
    LocationGeneric: hints.LocationGenericEndpoint
    LocationRack: hints.LocationRackEndpoint
    LocationSite: hints.LocationSiteEndpoint
    OrganizationGeneric: hints.OrganizationGenericEndpoint
    OrganizationManufacturer: hints.OrganizationManufacturerEndpoint
    OrganizationProvider: hints.OrganizationProviderEndpoint
    OrganizationTenant: hints.OrganizationTenantEndpoint
    ProfileBuiltinIPAddress: hints.ProfileBuiltinIPAddressEndpoint
    ProfileBuiltinIPPrefix: hints.ProfileBuiltinIPPrefixEndpoint
    ProfileBuiltinTag: hints.ProfileBuiltinTagEndpoint
    ProfileInfraAutonomousSystem: hints.ProfileInfraAutonomousSystemEndpoint
    ProfileInfraBGPPeerGroup: hints.ProfileInfraBGPPeerGroupEndpoint
    ProfileInfraBGPSession: hints.ProfileInfraBGPSessionEndpoint
    ProfileInfraBackBoneService: hints.ProfileInfraBackBoneServiceEndpoint
    ProfileInfraCircuit: hints.ProfileInfraCircuitEndpoint
    ProfileInfraCircuitEndpoint: hints.ProfileInfraCircuitEndpointEndpoint
    ProfileInfraDevice: hints.ProfileInfraDeviceEndpoint
    ProfileInfraEndpoint: hints.ProfileInfraEndpointEndpoint
    ProfileInfraInterface: hints.ProfileInfraInterfaceEndpoint
    ProfileInfraInterfaceL2: hints.ProfileInfraInterfaceL2Endpoint
    ProfileInfraInterfaceL3: hints.ProfileInfraInterfaceL3Endpoint
    ProfileInfraLagInterface: hints.ProfileInfraLagInterfaceEndpoint
    ProfileInfraLagInterfaceL2: hints.ProfileInfraLagInterfaceL2Endpoint
    ProfileInfraLagInterfaceL3: hints.ProfileInfraLagInterfaceL3Endpoint
    ProfileInfraMlagDomain: hints.ProfileInfraMlagDomainEndpoint
    ProfileInfraMlagInterface: hints.ProfileInfraMlagInterfaceEndpoint
    ProfileInfraMlagInterfaceL2: hints.ProfileInfraMlagInterfaceL2Endpoint
    ProfileInfraMlagInterfaceL3: hints.ProfileInfraMlagInterfaceL3Endpoint
    ProfileInfraPlatform: hints.ProfileInfraPlatformEndpoint
    ProfileInfraService: hints.ProfileInfraServiceEndpoint
    ProfileInfraVLAN: hints.ProfileInfraVLANEndpoint
    ProfileIpamIPAddress: hints.ProfileIpamIPAddressEndpoint
    ProfileIpamIPPrefix: hints.ProfileIpamIPPrefixEndpoint
    ProfileIpamNamespace: hints.ProfileIpamNamespaceEndpoint
    ProfileLocationGeneric: hints.ProfileLocationGenericEndpoint
    ProfileLocationRack: hints.ProfileLocationRackEndpoint
    ProfileLocationSite: hints.ProfileLocationSiteEndpoint
    ProfileOrganizationGeneric: hints.ProfileOrganizationGenericEndpoint
    ProfileOrganizationProvider: hints.ProfileOrganizationProviderEndpoint
    ProfileOrganizationTenant: hints.ProfileOrganizationTenantEndpoint
