"""Regenerate the typed kind hints from an Infrahub schema.

Outputs two files:

- src/aiopyinfrahub/kinds_generated.py - KindHints, one annotation per kind
- src/aiopyinfrahub/hints_generated.pyi - stub-only per-kind classes with
  TypedDict-backed kwargs overloads for filter/get/count/create/upsert

Usage:

    uv run scripts/generate_kinds.py [--url URL] [--token TOKEN]
                                     [--branch BRANCH] [--schema PATH]

Defaults to the public sandbox, which serves /api/schema and /api/info to
anonymous readers. Unlike the sisters there is no OpenAPI document to read:
kinds are whatever an instance's schema defines, so the checked-in hints
describe the sandbox's demo dataset and nothing more. A kind this file
misses still works at runtime, because Api.__getattr__ builds every
KindEndpoint dynamically; it just gets no autocomplete.

To generate against your own instance, or offline from a saved
/api/schema response:

    uv run scripts/generate_kinds.py --url https://infrahub.example.com \\
        --token "$INFRAHUB_TOKEN" --branch main
    uv run scripts/generate_kinds.py --schema sandbox_schema.json

The output is deterministic for a given schema. Both files are checked in
after `uv run ruff format`, which is what wraps the long signatures.
"""

from __future__ import annotations

import argparse
import json
import keyword
from pathlib import Path
from typing import Any

import httpx

DEFAULT_URL = "https://sandbox.infrahub.app"

SRC = Path(__file__).resolve().parent.parent / "src" / "aiopyinfrahub"

# The /api/schema sections that carry node schemas: `main` is the schema
# hash and `namespaces` a summary, neither of which describes a kind. Same
# list as schema.SCHEMA_SECTIONS, repeated so the script stays standalone.
SCHEMA_SECTIONS = ("nodes", "generics", "profiles", "templates")

# Filters every kind accepts. `hfid` is per kind instead: the server
# rejects it unless the kind's schema defines a human_friendly_id.
BASE_FILTERS = ("ids", "limit", "offset", "partial_match")

# Real attributes on Api that a kind annotation must never shadow. Kinds
# are PascalCase (namespace + name) and these are not, so nothing should
# ever hit this; the guard is here because a shadowed attribute would fail
# silently, as an endpoint that never resolves.
RESERVED = {
    "aclose",
    "artifacts",
    "base_url",
    "branch",
    "branches",
    "check_schemas",
    "convert_object_type",
    "diff",
    "graph",
    "graphql",
    "kind",
    "load_schemas",
    "login",
    "logout",
    "max_concurrency",
    "page_size",
    "pools",
    "retries",
    "schema",
    "schema_in_sync",
    "search",
    "storage",
    "tasks",
    "token",
    "transforms",
    "username",
    "version",
    "wait_schemas_converged",
}

# The read methods' keyword-only params, repeated in the typed overloads so
# that a call passing filters *and* branch=/at=/include=/exclude=/properties=
# still matches them rather than falling through to the **kwargs: Any overload.
READ_KW = "branch: str | None = None, at: str | None = None"
SELECT_KW = (
    "include: list[str] | None = None, exclude: list[str] | None = None, "
    "properties: bool = False"
)
# Mutations take no `at`: the server resets it to now.
WRITE_KW = "branch: str | None = None"

KINDS_HEADER = '''"""Typed kind hints generated from an Infrahub schema.

Generated by scripts/generate_kinds.py - do not edit by hand.
Source: {source} (Infrahub {version})

The kind annotations exist only for static analysis (autocomplete, type
checking); no attributes are created at runtime. Api.__getattr__ builds
every KindEndpoint dynamically, so kinds missing from this list - anything
another instance's schema defines - still work, and the hint classes in
hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aiopyinfrahub import hints_generated as hints


class KindHints:
    """One annotation per schema kind, inherited by Api."""
'''

HINTS_HEADER = '''"""Stub-only kwargs hints generated from an Infrahub schema.

Generated by scripts/generate_kinds.py - do not edit by hand.
Source: {source} (Infrahub {version})

This module exists only as a stub (.pyi): it is never imported at runtime,
and every runtime kind object is a plain KindEndpoint. The TypedDicts carry
filter and field names for autocomplete; values are Any so nothing is
enforced, and the trailing **kwargs: Any overloads keep everything the
schema does not list (deeper relationship traversals, another instance's
kinds) legal. Returns stay Record / RecordSet / int: no per-kind Record
subclasses are generated, so there is nothing to narrow them to.
"""

from typing import Any, TypedDict, Unpack, overload

from aiopyinfrahub.kinds import KindEndpoint
from aiopyinfrahub.response import Record, RecordSet
'''


def usable(name: str) -> bool:
    """Whether a name can be a TypedDict key or a class annotation."""
    return name.isidentifier() and not keyword.iskeyword(name)


def kind_name(node_schema: dict[str, Any]) -> str:
    """The GraphQL type name for a node schema, namespace + name.

    The `Attribute` namespace is elided by the server, as in schema.py.
    """
    namespace = node_schema.get("namespace") or ""
    name = node_schema.get("name") or ""
    return name if namespace == "Attribute" else f"{namespace}{name}"


def flatten(data: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Collapse a /api/schema response into one {kind: node_schema} map."""
    kinds: dict[str, dict[str, Any]] = {}
    for section in SCHEMA_SECTIONS:
        for node_schema in data.get(section) or []:
            kinds[kind_name(node_schema)] = node_schema
    return kinds


def filter_keys(
    node_schema: dict[str, Any], kinds: dict[str, dict[str, Any]]
) -> list[str]:
    """Filter names for one kind: base, attributes, relationships.

    Relationships traverse exactly one level into the peer's attributes,
    which is where the useful `site__name__value` form comes from. Deeper
    traversals are legal but unbounded, so they are left to the
    **kwargs: Any overload rather than multiplying the hint size.
    """
    keys = set(BASE_FILTERS)
    if node_schema.get("human_friendly_id"):
        keys.add("hfid")
    for attr in node_schema.get("attributes") or []:
        name = attr["name"]
        keys |= {f"{name}__value", f"{name}__values", f"{name}__isnull"}
    for rel in node_schema.get("relationships") or []:
        name = rel["name"]
        keys |= {f"{name}__ids", f"{name}__isnull"}
        peer = kinds.get(rel.get("peer") or "")
        if peer is None:
            continue  # peer kind absent from this payload; skip its filters
        for attr in peer.get("attributes") or []:
            keys.add(f"{name}__{attr['name']}__value")
    return sorted(key for key in keys if usable(key))


def field_keys(node_schema: dict[str, Any]) -> list[str]:
    """Writable field names for one kind: attributes and relationships."""
    names = {attr["name"] for attr in node_schema.get("attributes") or []}
    names |= {rel["name"] for rel in node_schema.get("relationships") or []}
    return sorted(name for name in names if usable(name))


def typed_dict(name: str, keys: list[str]) -> list[str]:
    """One name-completion TypedDict; values are Any so nothing is enforced."""
    if not keys:
        # A kind with no attributes and no relationships (a bare generic).
        return [f"class {name}(TypedDict, total=False): ..."]
    return [f"class {name}(TypedDict, total=False):"] + [
        f"    {key}: Any" for key in keys
    ]


def overload(name: str, params: str, returns: str, *, sync: bool = False) -> list[str]:
    """One @overload stub for a KindEndpoint method."""
    prefix = "def" if sync else "async def"
    return ["    @overload", f"    {prefix} {name}(self, {params}) -> {returns}: ..."]


def kind_stub(
    kind: str, filters: list[str], fields: list[str], *, creatable: bool = True
) -> str:
    """One kind's TypedDicts + KindEndpoint subclass for hints_generated.pyi.

    Every typed overload is followed by a fallback matching the runtime
    signature in kinds.py exactly, which is both what keeps unlisted
    filters legal and what makes the override assignable to the base.

    Generics get no create/upsert overloads: the server generates only
    <Kind>Update for them, so field completion would advertise mutations
    that cannot succeed. The base KindEndpoint signatures still apply.
    """
    read = f"*, {READ_KW}, {SELECT_KW}"  # filter/get take a field selection
    typed = f"**filters: Unpack[{kind}Filters]"
    out = typed_dict(f"{kind}Filters", filters)
    out.append("")
    out += typed_dict(f"{kind}Fields", fields)
    out.append("")
    out.append(f"class {kind}Endpoint(KindEndpoint):")
    out += overload("filter", f"{read}, {typed}", "RecordSet", sync=True)
    out += overload("filter", f"{read}, **filters: Any", "RecordSet", sync=True)
    out += overload("get", f"{read}, {typed}", "Record | None")
    out += overload(
        "get", f"pk: str | None = None, /, {read}, **filters: Any", "Record | None"
    )
    out += overload("count", f"*, {READ_KW}, {typed}", "int")
    out += overload("count", f"*, {READ_KW}, **filters: Any", "int")
    if creatable:
        for action in ("create", "upsert"):
            out += overload(
                action, f"*, {WRITE_KW}, **kwargs: Unpack[{kind}Fields]", "Record"
            )
            out += overload(
                action,
                f"fields: dict[str, Any] | None = None, /, *, {WRITE_KW}, "
                "**kwargs: Any",
                "Record",
            )
    return "\n".join(out)


def fetch(url: str, headers: dict[str, str], params: dict[str, str] | None) -> Any:
    resp = httpx.get(
        url, headers=headers, params=params, follow_redirects=True, timeout=300
    )
    resp.raise_for_status()
    return resp.json()


def server_version(url: str, headers: dict[str, str], data: dict[str, Any]) -> str:
    """The instance version, falling back to the schema's own hash.

    /api/info can be closed off on an instance that still serves
    /api/schema, and it is not reachable at all when generating from a
    saved payload, so the hash stands in as the identifier.
    """
    try:
        version = fetch(f"{url}/api/info", headers, None).get("version")
    except (httpx.HTTPError, ValueError):
        version = None
    return version or f"schema {data.get('main', 'unknown')}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--url", default=DEFAULT_URL, help=f"Infrahub base URL (default {DEFAULT_URL})"
    )
    parser.add_argument(
        "--token", help="API token, sent as X-INFRAHUB-KEY; the sandbox needs none"
    )
    parser.add_argument("--branch", help="branch whose schema to read")
    parser.add_argument(
        "--schema",
        type=Path,
        help="read a saved /api/schema response instead of the network",
    )
    args = parser.parse_args()

    url = args.url.rstrip("/")
    headers = {"Accept": "application/json"}
    if args.token:
        headers["X-INFRAHUB-KEY"] = args.token

    if args.schema:
        data = json.loads(args.schema.read_text(encoding="utf-8"))
        # A snapshot still describes an instance, so the header names that
        # instance (and the file) rather than a bare local path.
        source = f"{url} snapshot {args.schema.name}"
        version = f"schema {data.get('main', 'unknown')}"
    else:
        params = {"branch": args.branch} if args.branch else None
        data = fetch(f"{url}/api/schema", headers, params)
        source = f"{url}?branch={args.branch}" if args.branch else url
        version = server_version(url, headers, data)

    kinds = flatten(data)
    names = sorted(k for k in kinds if usable(k) and k not in RESERVED)
    generics = {kind_name(n) for n in data.get("generics") or []}

    hints_chunks = [HINTS_HEADER.format(source=source, version=version)]
    annotations = []
    total_filters = 0
    for kind in names:
        filters = filter_keys(kinds[kind], kinds)
        total_filters += len(filters)
        hints_chunks.append(
            kind_stub(
                kind,
                filters,
                field_keys(kinds[kind]),
                creatable=kind not in generics,
            )
        )
        annotations.append(f"    {kind}: hints.{kind}Endpoint")

    header = KINDS_HEADER.format(source=source, version=version)
    write(SRC / "kinds_generated.py", header + "\n" + "\n".join(annotations))
    write(SRC / "hints_generated.pyi", "\n\n".join(hints_chunks))
    print(
        f"wrote kinds_generated.py + hints_generated.pyi ({len(names)} kinds, "
        f"{total_filters} filter keys, Infrahub {version})"
    )


def write(path: Path, text: str) -> None:
    # newline="\n" because these are generated on whatever platform the
    # maintainer runs, and the repo is LF (.editorconfig).
    path.write_text(text + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
